# Generated by Django 5.0.6 on 2026-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addskills',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='i_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='idCard',
            field=models.FileField(default='', upload_to='id/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
