# Generated by Django 5.0.6 on 2026-02-05 14:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0002_student_addskills_student_i_id_student_idcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idCard',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
