# Generated by Django 5.0.6 on 2026-02-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0003_alter_student_idcard_alter_student_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='idCard',
            new_name='id_card',
        ),
    ]
