# Generated by Django 5.0.6 on 2026-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_adress_remove_customuser_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_verification',
            field=models.IntegerField(max_length=999999, null=True),
        ),
    ]
